# Generated by Django 5.2.17 on 2026-09-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_requests', '0016_itemrequest_closed_status'),
        ('matching', '0005_connected_match_statuses'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, db_index=True, max_length=32)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(default='reply', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'outreach opt-out',
                'verbose_name_plural': 'outreach opt-outs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopped', models.BooleanField(default=False, help_text='Stop all sending right away (no redeploy needed).')),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=64)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'outreach state',
                'verbose_name_plural': 'outreach state',
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_username', models.CharField(db_index=True, max_length=32)),
                ('text', models.TextField()),
                ('token', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('recipient_telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_message', to='item_requests.itemrequest')),
                ('matches', models.ManyToManyField(blank=True, related_name='outreach_messages', to='matching.match')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to='users.user')),
            ],
            options={
                'verbose_name': 'outreach message',
                'verbose_name_plural': 'outreach messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
