# Generated by Django 5.2.17 on 2026-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachmessage',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('HELD', 'Held for review')], db_index=True, default='QUEUED', max_length=16),
        ),
    ]
