# Generated by Django 5.2.17 on 2026-08-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_requests', '0002_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED_BY_SUPPLY', 'Accepted by supply'), ('ACCEPTED_BY_DEMAND', 'Accepted by demand'), ('CONNECTED', 'Connected'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='SUGGESTED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_matches', to='item_requests.itemrequest')),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_matches', to='item_requests.itemrequest')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='matching_ma_status_8042fa_idx'), models.Index(fields=['score'], name='matching_ma_score_8af64e_idx')],
                'unique_together': {('demand_request', 'supply_request')},
            },
        ),
    ]
