# Generated by Django 5.2.17 on 2026-09-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATCH_PROBLEM', 'Match Problem'), ('CANNOT_CONTACT_USER', 'Cannot Contact User'), ('REPORT_USER', 'Report User'), ('TECHNICAL_ISSUE', 'Technical Issue'), ('OTHER', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_QUEUE', 'In Queue'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=16, null=True)),
                ('last_admin_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='users.user')),
            ],
            options={
                'verbose_name': 'support ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=16)),
                ('sender_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'support message',
                'verbose_name_plural': 'support messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'updated_at'], name='support_sup_status_e12ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'updated_at'], name='support_sup_user_id_2a0b74_idx'),
        ),
    ]
