# Generated by Django 5.2.17 on 2026-08-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=64)),
                ('name_fa', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name_en', models.CharField(max_length=64)),
                ('name_fa', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('name_fa', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='item_requests.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name_en'],
                'unique_together': {('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEMAND', 'Demand'), ('SUPPLY', 'Supply')], max_length=16)),
                ('origin_country', models.CharField(max_length=2)),
                ('origin_city', models.SlugField(max_length=64)),
                ('destination_country', models.CharField(max_length=2)),
                ('destination_city', models.SlugField(max_length=64)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('excluded_other_text', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='excluded_by_requests', to='item_requests.category')),
                ('item_categories', models.ManyToManyField(blank=True, related_name='item_requests', to='item_requests.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='users.user')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='item_reques_type_16e81e_idx'), models.Index(fields=['origin_country', 'origin_city'], name='item_reques_origin__572ec3_idx'), models.Index(fields=['destination_country', 'destination_city'], name='item_reques_destina_b993de_idx')],
            },
        ),
    ]
